# Site Settings
baseurl: ""
url : "https://zairewilson20.github.io"

# Blog Settings
theme_settings :
  title : Zaire Wilson
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/ZAvatar.webp
    username : Zaire Wilson
    description : Programmer of Games, Watcher of Anime, Father of Cats
    experience :
      - start : December 2024
        end : Present
        experience : Scientific Research Corporation, Software Developer II
      - start : September 2024
        end : Present
        experience : Five Mics, Lead Engineer
      - start : January 2022
        end : September 2024
        experience : GOLF+, Software Engineer
      - start : July 2021
        end : January 2022
        experience : Metagaming Studios, Software Engineer
      - start : May 2019
        end : January 2020
        experience : Rensselaer Polytechnic Institute, Undergrad Researcher
    education :
      - start : August 2020
        end : May 2021
        school : Rensselaer Polytechnic Institute
        degree: M.S. Critical Game Design
      - start : August 2016
        end : May 2020
        school : Rensselaer Polytechnic Institute
        degree: B.S. Game and Simulation, Arts and Science + Computer Science

        
  # Icons
  icons :
    email:  zaire.r.wilson@gmail.com
    linkedin:  https://www.linkedin.com/in/zairewilson/ 
    github: ZaireWilson20
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
